name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.6'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Install poetry
      uses: abatilo/actions-poetry@v2.0.0
    - name: Setup python
      run: poetry install
    - name: Run tests
      run: poetry run pytest
    - name: Build package
      run: poetry build
    - name: Create environment variables
      env:
        POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
    - name: Publish package
      run: poetry publish
      
      
      
      
      
      
      
      
      
      
      
